import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import { ToastContainer } from "react-toastify";
import { AuthUserStoreProvider } from "@/providers/auth-user-store-provider";
import { UserStoreProvider } from "@/providers/user-store-provider";
import { TanStackQueryClientProvider } from "@/providers/tanstack-query-client-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanStackQueryClientProvider>
          <AuthUserStoreProvider>
            <UserStoreProvider>
              <Provider>
                <ToastContainer position="top-center" />
                {children}
              </Provider>
            </UserStoreProvider>
          </AuthUserStoreProvider>
        </TanStackQueryClientProvider>
      </body>
    </html>
  );
}
